### ISSUE TITLE
Add Upgrades as a Lua Library

### ISSUE THREAD

**Issue by MNoya** [cowsforyou/barracks_master_2#21]
Extends tech_tree.kv system, making it flexible for this and other customs that want to setup ability upgrades through research

**Comment by MNoya** [comment]
Started on 119d138742e0a62a08f69034677425def5c3717d
Just added a single builder _disabled ability, will need to add more to test research and creep abilities

**Comment by cowsforyou** [comment]
I saw this. Seems to work by default but it breaks if you click next then back (via the ability swapper).

**Comment by MNoya** [comment]
This should be working now
