### ISSUE TITLE
Upgrade Building Helper library

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master_2#22]
To add the following:

- [ ] An equivalent for "modifier_construction". - Per race
- [x] Show destruction particle when buildings are destroyed (currently only shows if building is canceled).
- [x] If possible, add a max building count check as well (so I can limit the number of times a building can be constructed). `BuildingHelper:GetBuildingCount(playerID, buildingName)` returns a number with how many of that building does the player have. The library takes care of updating this value +1/-1 whenever a building **finishes** construction or is **killed**

**Comment by MNoya** [comment]
`modifier_construction` should be flexible and check for a "ConstructionEffect" for different construction effects for each building

**Comment by MNoya** [comment]
Started https://github.com/MNoya/BuildingHelper/releases/tag/1.1.5

Added `BuildingHelper:GetBuildingCount(playerID, buildingName)` which should help implementing the restriction counts very easily via `builder.lua` callbacks

By equivalent for "modifier_construction", I added `building:IsUnderConstruction()` for detection (much better than relying on a modifier), not sure if we needed modifier_construction for particle effects but that can also be done in builder callbacks. If having a `"ConstructionEffect"` is interesting, I can add that on next library version.

**Comment by MNoya** [comment]
Modifiers by name can be applied via `ApplyModifier(unit, "modifier_something") with https://github.com/cowsforyou/barracks_master_2/blob/master/game/dota_addons/barracks_master_2/scripts/vscripts/widgets/apply_modifier.lua

They are defined in item_apply_modifiers.txt https://github.com/cowsforyou/barracks_master_2/blob/master/game/dota_addons/barracks_master_2/scripts/npc/items/item_apply_modifiers.txt
