### ISSUE TITLE
Create lua codes to spawn towers and ancients

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master_2#29]
You can use the map bm2_cold_war.vmap as a testbed. 

The map has two lanes with tower tiers 1-4. I have the towers spawned there as npc_dota_base entities. The naming convention is:

tower_lane1_tier1_team2
tower_lane1_tier2_team2
etc

tower_lane2_tier1_team2
tower_lane2_tier2_team2
etc

tower_lane1_tier1_team3
tower_lane1_tier2_team3
etc

The map currently has 16 towers on it.

To spawn the ancients, we can use the default npc file provided by valve. No need to create unique ones.

The towers and ancient should have invulnerability link counts but no backdoor protection.

**Comment by MNoya** [comment]
> To spawn the ancients, we can use the default npc file provided by valve. No need to create unique ones.

I might have backdoor protection this way but we'll get down to that later, doing the towers first

**Comment by MNoya** [comment]
Towers done in 4c5f34043ea49f582ee9741dfff2396789c86e0f
