### ISSUE TITLE
Issues with Dire Towers

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master_2#34]
- [x] Towers are facing backwards
- [x] Towers display ERROR under fog - https://gfycat.com/SorrowfulDeficientChimpanzee

**Comment by cowsforyou** [comment]
@MNoya The ERROR under fog seems fixed but I think the towers are still facing backwards.

**Comment by MNoya** [comment]
Fixed on 8fe8481797ed7397ccf5b4dfd9914c80de578a6d
