### ISSUE TITLE
First AI Attempt

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master_2#35]
So one of the units I wanted to make for Xoya was a Nyx that would follow the wave, and when it gets near an enemy, it burrows and starts using impale over and over again (with a reasonable cooldown of course). When there are no more enemies within range, it crawls back up to the surface, continues on it's path until it meets new enemies and the process repeats again.

**Comment by cowsforyou** [comment]
Ok I added the base model for you and added the abilities required as well: https://github.com/cowsforyou/barracks_master_2/commit/4740812c479275f2f3a5a43d3a52aac3fa15e204

I couldn't get the burrow to show up? But I managed to get the unburrow to appear. Tried using the ability override file - have a look and see if I did anything wrong.

**Comment by MNoya** [comment]
This would be a small AI just for the creep, right?

I have a burrow reword on dotacraft, better we just use that one than deal with any hardcoded dota ability shenanigans

**Comment by cowsforyou** [comment]
@MNoya Yeah just a small AI on this particular creep. And honestly, probably the most complex one that I have planned. The others are much simpler: Either just casting a nuke on the enemy or casting a buff on an ally. 

And yup I'm perfectly cool with using your custom burrow ability on Dotacraft!

**Comment by cowsforyou** [comment]
Merging with https://github.com/cowsforyou/barracks_master_2/issues/71
