### ISSUE TITLE
Add Giant Trees

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master_2#39]
Giant Trees will be neutral units on the map that workers can go to and harvest (similar to gold mine on Dotacraft). 

I'm thinking of adding two different tiers of trees with different amounts of total lumber that can be harvested.

**Comment by cowsforyou** [comment]
@MNoya should I place the trees on hammer or use lua to do it (similar to the towers).

**Comment by MNoya** [comment]
Lua would be better, as a "giant_tree" unit with a big model scale. If we follow the gold_mine system,

**Comment by cowsforyou** [comment]
https://github.com/cowsforyou/barracks_master_2/commit/573d75d65489a5b9d1c823526cbfe72aeddc2bcf
