### ISSUE TITLE
Setup MaxBuildingCount

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master_2#50]
We discussed this a few times on the chat - I forgot what the current status of this is.

**Comment by MNoya** [comment]
Currently we have an API function on `BuildingHelper:GetBuildingCount(name)` but its not being called, it would be just adding the check on builder.lua, will take care of it

**Comment by cowsforyou** [comment]
Noted! :)

**Comment by cowsforyou** [comment]
MaxBuildingCount not respected if queue is set prior to completing the building.

http://i.imgur.com/fOWohnk.png
