### ISSUE TITLE
Lumber values get duplicated on UI

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master_2#51]
I think the ability swapper has some interface issues with the lumber UI. After hitting the next button it still retains the same lumber values. 

http://i.imgur.com/6BeqAc3.png

Probably need to add a refresh/check for the somewhere?

**Comment by MNoya** [comment]
Yeah, need to call `FireGameEvent( 'ability_values_force_check', {player_ID = playerID})`
