### ISSUE TITLE
Various bugs with research/abilities/build

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master_2#59]
- [x] a) Abilities stay at level 1 despite research being upgraded further
- [x] b) Research abilities can be upgraded further despite hitting maximum level
- [x] c) MaxBuildingCount not respected
- [x] d) Tech Tree not working for buildings

Repro steps:
1a) Upgrade Citol Armor 2 or 3 times
2a) The creeps will still have the armor bonus at level 1

1b) Upgrade Citol Armor over and over again
2b) You should be able to continuously upgrade even after hitting the level 3 cap

1c) Build two Cavern of Citol

1d) Build Cavern of Citol
2d) Build Cavern of Phe
3d) Tower of Catl'ix still not unlocked

**Comment by MNoya** [comment]
Close if everything is working
