### ISSUE TITLE
Lumber cost doesn't appear unless refreshed

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master_2#64]
If a build ability is unlocked, the lumber cost doesn't appear unless refreshed (via ability swapper, or by clicking on something else, etc).

http://i.imgur.com/1izezYH.png

**Comment by MNoya** [comment]
This won't be used anymore, gotta do the lumber on the image icon or make a new system (but there isn't a good way to do it in panorama, as the scaleform tooltip will be rendered on top)
